### ISSUE TITLE
New Studentenwerk homepage

### ISSUE THREAD

**Issue by kaifabian** [kaifabian/om-parser-potsdam#3]
Studentenwerk Potsdam has completely changed their homepage, and with that, the daily/weekly menu page. Thus, om-parser-potsdam does not work anymore.

om-parser-potsdam would need a complete rewrite.

The new format seems much more easily parsable (structured div with useful class attributes, etc.).
Now it needs to be decided, whether I will have time to completely re-implement this parser (or whether there will be someone else up to the "challenge").

**Comment by f4lco** [comment]
Hi @kaifabian, I've followed your advice and attempted a rewrite over at [f4lco/om-parser-stw-potsdam-v2](https://github.com/f4lco/om-parser-stw-potsdam-v2). I believe it looks promising and basic functionality is working, although probably feature-incomplete. There is more metadata to be provided to OpenMensa & one could invest into error handling (something which I think is not covered in the parser docs).

If possible, I really would like to join forces. I just did not dare to open a PR which practically annihilates  what is already there. I'd be glad if you could take a look at the repo and tell me what you think of the existing code and what you would have approached differently.

**Comment by kaifabian** [comment]
Hi @f4lco, everything I see so far looks very promising. I can not completely check out this code since I'm on vacation until 30th this month, and any "code review" on a mobile device is not really enjoyable.

I wouldn't reject any pull request that completely annihilates this repository, since this repository here is, to be honest, full of crap. I was in my 2nd semester of my Bachelor's degree, I just started coding Python and frankly: I did not know any better. ;)
But on the other hand, it would not really make sense to push a completely new codebase into this repository just for the sake of "keeping the repository alive". I am not invested in this repository (anymore), and if it is your code, then you should be the one getting full credit.

Since I am not a student at University of Potsdam anymore, and I won't be regularly visiting any of Potsdam canteens anytime soon, I am not really invested in still providing an OpenMensa feed for those canteens. If you feel up to the task, I'd be glad to close down my repository and exclusively link to your code in my README.

Another question remaining is: can you host it yourself or do you need some support in that way? If you can host it yourself, I will get in touch with @jgraichen and/or @mswart so that we find a way to update the feed URLs for Potsdam's canteens and transfer ownership to your OpenMensa account.

**Comment by kaifabian** [comment]
So far, the repo redirect is done.

I just forked your repo. Next things I would do are:
- create a Dockerfile in my fork, so that your parser can easily deployed in my Docker infrastructure, and send you a pull request
- create a "production" branch in my repository which will automatically get deployed on my infrastructure

Then, all deployments can be triggered by a pull request into my "production" branch (and will get deployed once I accept that PR).

Is that okay with you?

**Comment by f4lco** [comment]
Yes that is perfectly fine with me :)
Thank you very much for your effort, will go through your PRs in a sec.

**Comment by kaifabian** [comment]
[kaifabian/om-parser-potsdam](/kaifabian/om-parser-potsdam) is dead, long live [f4lco/om-parser-stw-potsdam-v2](/f4lco/om-parser-stw-potsdam-v2)! :)

Any further comments/issues/etc. should be discussed there. Thus: closed.
